name: "CI"

on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  unit-test:
    name: "Unit Test"
    uses: na4ma4/actions/.github/workflows/unit-test.yml@main
    secrets: inherit
    with:
      enable-codecov: true
      enable-fossa: true
